stages:
  - test
  - build
  - package
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - ~/.cargo/registry
    - ~/.cargo/git

test:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings
    - cargo test --all
  tags:
    - alfonz

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/${CI_PROJECT_NAME}
    expire_in: 1 week
  tags:
    - alfonz


package:
  stage: package
  needs: [ "build" ]
  script:
    - mkdir dist
    - cp target/release/${CI_PROJECT_NAME} dist/
    - tar -czf dist/${CI_PROJECT_NAME}-linux.tar.gz -C dist ${CI_PROJECT_NAME}
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  tags:
    - alfonz

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: [ "package" ]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/'
  script:
    - echo "Publishing assets for $CI_COMMIT_TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    name: 'Release $CI_COMMIT_TAG'
    description: |
      Automated release generated by the CI pipeline for **$CI_COMMIT_TAG**.
    assets:
      links:
        - name: Linux binary
          filepath: "dist/${CI_PROJECT_NAME}-linux.tar.gz"
  tags:
    - alfonz
