[package]
name = "nftables-blocklist-updater"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
ureq = "3.0.11"
env_logger = "0.11.8"
log = "0.4.22"
ipnet = "2.11.0"
thiserror = "2.0.12"
